spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.167:3306/dbmall-goods?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: mysql_sony
    password: root

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.goku.realEstate.goods.dao.po